import { defineConfig } from 'tsup';

export default defineConfig({
    entry: ['src/components/index.ts'],
    dts: true,
    format: ['esm', 'cjs'],
    outDir: 'dist',
    clean: true,
    treeshake: 'recommended',
    minify: true,
    sourcemap: false,
    external: [
        'react',
        'react-dom',
        '@radix-ui/react-accordion',
        '@radix-ui/react-aspect-ratio',
        '@radix-ui/react-checkbox',
        '@radix-ui/react-collapsible',
        '@radix-ui/react-context-menu',
        '@radix-ui/react-dialog',
        '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-hover-card',
        '@radix-ui/react-label',
        '@radix-ui/react-navigation-menu',
        '@radix-ui/react-popover',
        '@radix-ui/react-progress',
        '@radix-ui/react-radio-group',
        '@radix-ui/react-scroll-area',
        '@radix-ui/react-select',
        '@radix-ui/react-slider',
        '@radix-ui/react-switch',
        '@radix-ui/react-tabs',
        '@radix-ui/react-toast',
        '@radix-ui/react-tooltip',
    ],
    tsconfig: 'tsconfig.build.json',
});
